---
title: "Alto Voltaje"
author: 
  - name: Alicia Sanchez Alberca
  - name: César García Asto
  - name: Daniel Aguilar Paucar
  - name: Giuliano Morales Moreyra
format: 
  html:
    toc: true
    toc_depth: 6
    embed-resources: true
    code-fold: true
    error: false
    warning: false
    code-tools: true
    code-copy: true
editor: visual
output: asis
theme: cosmo 
---

**Card Deck**

The card deck is generated according to the following logic:

-   "There are 73 cards. Each card has a main number from 1 to 10 and a modifier number ± 1 to 3"

```{r}
# Create the main numbers and modifiers
main_numbers <- 1:10
modifiers <- c((-1:-3), (1:3))

# Generate all combinations
card_deck <- expand.grid(Main_Number = main_numbers, Modifier = modifiers) |> dplyr::mutate(Value = Main_Number + Modifier)
```

## 1. Creating a stochastic 73 card deck

```{r}
draw_n_cards <- function(n = 73){
  #1. equal probability of drawing a card with numbers 1 trough 10
  
  main_numbers <- round(runif(n = n,min = 1,max = 10))
  main_numbers
  
  #2. equal probability of drawing a card with numbers -1 trough -3 and 1 trough 3
  #2.1 Generate n positive and negative values
  modifiers_pos <- round(runif(n, min = -3, max = -1))
  modifiers_neg <- round(runif(n, min = 1, max = 3))
  #2.2 Randomly choose n from both positive and negative values
  modifiers <- c(modifiers_pos, modifiers_neg)
  modifiers <- sample(x = modifiers,size = n)
  
  #3. Output Dataframe
  output <- data.frame(main_numbers = main_numbers, modifiers = modifiers)
  return(output)
}
```

Testing

```{r}

a <- draw_n_cards()
a
```

## 2. Draw n cards for m-players

```{r}
draw_n_cards_for_m_players <- function(n = 10, m = 2){
  cards <- list()
  for(i in 1:m){
    player_name <- paste0("Player_",i) 
    cards_drawn <- draw_n_cards(n = n) |> 
      dplyr::mutate(player_name = player_name)
    cards[[player_name]] <- cards_drawn
  }
  return(cards)
}
test <- draw_n_cards_for_m_players(n = 73, m = 2)
```
